name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo source code
        uses: actions/checkout@v3

      - name: Display PowerShell version being used
        shell: pwsh
        run: $PSVersionTable

      - name: Run PowerShell linter with PSScriptAnalyzer
        shell: pwsh
        run: |
          Write-Output "Running PSScriptAnalyzer against all PowerShell files in the repo:"
          Invoke-ScriptAnalyzer -Path . -Recurse -ExcludeRule PSAvoidUsingWriteHost -EnableExit -Outvariable issues

          # $errors = $issues | Where-Object { $_.Severity -eq 'Error' }
          # $warnings = $issues | Where-Object { $_.Severity -eq 'Warning' }

          # if ($errors -or $warnings)
          # {
          #     throw "PSScriptAnalyzer found $($errors.Count) errors and $($warnings.Count) warnings that need to be fixed."
          # }

      - name: Run Pester Tests
        shell: pwsh
        run: |
          Write-Output "Pester version being used:"
          Import-Module -Name Pester
          Get-Module -Name Pester

          Write-Output "Running all Pester tests in the repo:"
          Invoke-Pester
